import { Poppins } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Satria Keren",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <div className="flex flex-col w-full bg-red-400">
          <Navbar />
          <Sidebar />
          <div className="min-h-screen bg-gray-100 p-4 pl-[270px]">
            <div className="mt-20 w-full">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
